# Generated by Django 4.1.3 on 2022-11-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions_app', '0001_initial'),
        ('user_app', '0001_initial'),
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidders',
            name='bidder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='user_app.user'),
        ),
        migrations.AddField(
            model_name='automaticbidding',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_autobids', to='auctions_app.auctiondetails'),
        ),
        migrations.AddField(
            model_name='automaticbidding',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autobids', to='auctions_app.bidders'),
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='seller_app.productinformation'),
        ),
        migrations.AddField(
            model_name='allbids',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allauctionbids', to='auctions_app.auctiondetails'),
        ),
        migrations.AddField(
            model_name='allbids',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allbids', to='auctions_app.bidders'),
        ),
    ]
