# Generated by Django 4.1.3 on 2022-11-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinformation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_app.user'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller_app.productinformation'),
        ),
    ]
