# Generated by Django 4.1.3 on 2022-11-22 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='successauctions',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelledauctions',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_auctions', to='auction_app.auctiondetails'),
        ),
    ]
