# Generated by Django 4.1.3 on 2022-11-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions_app', '0002_initial'),
        ('reports_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='successauctions',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='s_owner', to='user_app.user'),
        ),
        migrations.AddField(
            model_name='cancelledauctions',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_auctions', to='auctions_app.auctiondetails'),
        ),
    ]
